include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    always_use_package_imports: error
    invalid_annotation_target: ignore

linter:
  rules:
    always_use_package_imports: true
    use_string_in_part_of_directives: true
