name: breed_api
description: Dart API Client for the Locker API.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  http: 1.2.2
  freezed_annotation: 2.4.4
  json_annotation: 4.9.0

dev_dependencies:
  build_runner: 2.4.11
  freezed: 2.5.7
  json_serializable: 6.8.0
